/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R2faSetupRouteImport } from './routes/2fa-setup'
import { Route as R2faVerifyRouteImport } from './routes/2fa-verify'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDomainRulesRouteImport } from './routes/_authenticated/domain-rules'
import { Route as AuthenticatedNodesRouteImport } from './routes/_authenticated/nodes'
import { Route as AuthenticatedPeersRouteImport } from './routes/_authenticated/peers'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'

const R2faSetupRoute = R2faSetupRouteImport.update({
  id: '/2fa-setup',
  path: '/2fa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faVerifyRoute = R2faVerifyRouteImport.update({
  id: '/2fa-verify',
  path: '/2fa-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDomainRulesRoute =
  AuthenticatedDomainRulesRouteImport.update({
    id: '/domain-rules',
    path: '/domain-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesRoute = AuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeersRoute = AuthenticatedPeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/2fa-setup': typeof R2faSetupRoute
  '/2fa-verify': typeof R2faVerifyRoute
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domain-rules': typeof AuthenticatedDomainRulesRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/peers': typeof AuthenticatedPeersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/servers': typeof AuthenticatedServersRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/claim/$token': typeof ClaimTokenRoute
}
export interface FileRoutesByTo {
  '/2fa-setup': typeof R2faSetupRoute
  '/2fa-verify': typeof R2faVerifyRoute
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domain-rules': typeof AuthenticatedDomainRulesRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/peers': typeof AuthenticatedPeersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/servers': typeof AuthenticatedServersRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/claim/$token': typeof ClaimTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/2fa-setup': typeof R2faSetupRoute
  '/2fa-verify': typeof R2faVerifyRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domain-rules': typeof AuthenticatedDomainRulesRoute
  '/_authenticated/nodes': typeof AuthenticatedNodesRoute
  '/_authenticated/peers': typeof AuthenticatedPeersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/claim/$token': typeof ClaimTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/2fa-setup'
    | '/2fa-verify'
    | '/'
    | '/login'
    | '/admins'
    | '/audit-log'
    | '/config'
    | '/dashboard'
    | '/domain-rules'
    | '/nodes'
    | '/peers'
    | '/profile'
    | '/servers'
    | '/statistics'
    | '/users'
    | '/claim/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/2fa-setup'
    | '/2fa-verify'
    | '/'
    | '/login'
    | '/admins'
    | '/audit-log'
    | '/config'
    | '/dashboard'
    | '/domain-rules'
    | '/nodes'
    | '/peers'
    | '/profile'
    | '/servers'
    | '/statistics'
    | '/users'
    | '/claim/$token'
  id:
    | '__root__'
    | '/2fa-setup'
    | '/2fa-verify'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admins'
    | '/_authenticated/audit-log'
    | '/_authenticated/config'
    | '/_authenticated/dashboard'
    | '/_authenticated/domain-rules'
    | '/_authenticated/nodes'
    | '/_authenticated/peers'
    | '/_authenticated/profile'
    | '/_authenticated/servers'
    | '/_authenticated/statistics'
    | '/_authenticated/users'
    | '/claim/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R2faSetupRoute: typeof R2faSetupRoute
  R2faVerifyRoute: typeof R2faVerifyRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/2fa-setup': {
      id: '/2fa-setup'
      path: '/2fa-setup'
      fullPath: '/2fa-setup'
      preLoaderRoute: typeof R2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa-verify': {
      id: '/2fa-verify'
      path: '/2fa-verify'
      fullPath: '/2fa-verify'
      preLoaderRoute: typeof R2faVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domain-rules': {
      id: '/_authenticated/domain-rules'
      path: '/domain-rules'
      fullPath: '/domain-rules'
      preLoaderRoute: typeof AuthenticatedDomainRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes': {
      id: '/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthenticatedNodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peers': {
      id: '/_authenticated/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof AuthenticatedPeersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainRulesRoute: typeof AuthenticatedDomainRulesRoute
  AuthenticatedNodesRoute: typeof AuthenticatedNodesRoute
  AuthenticatedPeersRoute: typeof AuthenticatedPeersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainRulesRoute: AuthenticatedDomainRulesRoute,
  AuthenticatedNodesRoute: AuthenticatedNodesRoute,
  AuthenticatedPeersRoute: AuthenticatedPeersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R2faSetupRoute: R2faSetupRoute,
  R2faVerifyRoute: R2faVerifyRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ClaimTokenRoute: ClaimTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
